import type { Metadata } from 'next'
import { DotMatrix } from '@/components/sfx/dot-matrix';
import { Icons } from '@/components/Icons';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Lex Wuestenenk',
    description: 'Generated by create next app',
}

export default function Projects() {
    return (
        <div className='bg-background h-screen flex justify-center items-center container overflow-clip select-none'>
            <DotMatrix />
            <Button asChild className='absolute bg-transparent border-2 border-primary hover:bg-transparent top-0 left-0 m-5 text-text'>
                <Link href="/">
                    Back to homepage
                </Link>
            </Button>
            <div className='flex justify-between items-center w-full z-10 pointer-events-none'>
                <div className='text-5xl'>
                    <h1 className='text-text'>My</h1>
                    <h1 className='text-primary'>Resume</h1>
                </div>
            </div>
        </div> 
    )
}