import type { Metadata } from 'next'
import { DotMatrix } from '@/components/sfx/dot-matrix';
import { CursorFollow } from '@/components/sfx/cursor-follow';
import { Icons } from '@/components/Icons';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Lex Wuestenenk',
    description: 'Generated by create next app',
}

export default function Projects() {
    return (
        <div className='bg-background h-screen flex justify-center items-center container overflow-clip select-none'>
            <CursorFollow />
            <DotMatrix />
            <Button asChild className='absolute bg-transparent border-2 border-primary hover:bg-transparent top-0 left-0 m-5 text-text'>
                <Link href="/">
                    Back to homepage
                </Link>
            </Button>
            <div className='flex justify-between items-center w-full z-10 pointer-events-none'>
                <div className='text-5xl'>
                    <h1 className='text-text'>My</h1>
                    <h1 className='text-primary'>Projects</h1>
                </div>
                <div className='flex flex-col gap-3 pr-14'>
                    <Link href="#">
                        <div className='border-2 border-primary rounded-md p-3 m-3 max-w-md text-text bg-background ease-in duration-300 hover:bg-primary cursor-pointer pointer-events-auto'>
                            <div className='flex flex-row justify-between'>
                                <h2 className='text-3xl mb-3'>Portfolio</h2>
                                <Icons.Link />
                            </div>
                            <p>
                                The site you are looking at right now. I build this when I started hosting websites on my Raspberry Pi, so I had something to host and could practice a bit of frontend. 
                            </p>
                        </div>
                    </Link>
                    <Link href="#">
                        <div className='border-2 border-primary rounded-md p-3 m-3 max-w-md text-text bg-background ease-in duration-300 hover:bg-primary cursor-pointer pointer-events-auto'>
                            <div className='flex flex-row justify-between'>
                                <h2 className='text-3xl mb-3'>Portfolio</h2>
                                <Icons.Link />
                            </div>
                            <p>
                                The site you are looking at right now. I build this when I started hosting websites on my Raspberry Pi, so I had something to host and could practice a bit of frontend. 
                            </p>
                        </div>
                    </Link>
                    <Link href="#">
                        <div className='border-2 border-primary rounded-md p-3 m-3 max-w-md text-text bg-background ease-in duration-300 hover:bg-primary cursor-pointer pointer-events-auto'>
                            <div className='flex flex-row justify-between'>
                                <h2 className='text-3xl mb-3'>Portfolio</h2>
                                <Icons.Link />
                            </div>
                            <p>
                                The site you are looking at right now. I build this when I started hosting websites on my Raspberry Pi, so I had something to host and could practice a bit of frontend. 
                            </p>
                        </div>
                    </Link>
                    <Link href="#">
                        <div className='border-2 border-primary rounded-md p-3 m-3 max-w-md text-text bg-background ease-in duration-300 hover:bg-primary cursor-pointer pointer-events-auto'>
                            <div className='flex flex-row justify-between'>
                                <h2 className='text-3xl mb-3'>Portfolio</h2>
                                <Icons.Link />
                            </div>
                            <p>
                                The site you are looking at right now. I build this when I started hosting websites on my Raspberry Pi, so I had something to host and could practice a bit of frontend. 
                            </p>
                        </div>
                    </Link>
                </div>
            </div>
        </div> 
    )
}